version: '2'

volumes:
  pulse:

services:

  pulseaudio:
    build: ./pulseaudio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - 'pulse:/run/pulse'

  bluetooth:
    build: ./bluetooth
    network_mode: host
    cap_add:
      - NET_ADMIN    
    labels:
      io.balena.features.dbus: 1

  pulsetest:
    build: ./pulsetest
    labels:
      io.balena.features.dbus: 1    
    volumes:
      - 'pulse:/run/pulse'