version: '2'

volumes:
  pulse:

services:

  pulseaudio:
    build: ./pulseaudio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    ports:
      - 4317:4317
    volumes:
      - 'pulse:/run/pulse'

  bluetooth:
    build: ./bluetooth
    network_mode: host
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: 1

  pulsetest:
    build: ./pulsetest
    volumes:
      - 'pulse:/run/pulse'
  
  # SOX using TCP sockets
  sox:
    build: ./examples/sox
    
  # MPlayer using UNIX sockets
  mplayer:
    build: ./examples/mplayer
    volumes:
      - 'pulse:/run/pulse'